// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Repository;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(IndexDbContext))]
    [Migration("20250918183635_Update2")]
    partial class Update2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CommonLib.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Metadata", "CommonLib.Models.Document.Metadata#DocumentMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Keywords")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NamedEntities")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("backend.Model.LexemeMetadata", b =>
                {
                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContainingDocuments")
                        .HasColumnType("INTEGER");

                    b.HasKey("Text");

                    b.ToTable("Lexemes");
                });
#pragma warning restore 612, 618
        }
    }
}
